scripts/bootstrap-prefix.sh: fix for >= glibc-2.35 in stage3
slyfox explains it well in the linked bugs, but
the gist is that we mostly got lucky for a while.

We would mix system crt*.o with just-built libc_nonshared.a/libc.so
which led to issues like:
```
configure:4383: x86_64-pc-linux-gnu-gcc -O2 -pipe -O2 -pipe  -L/home/share/gentoo/usr/lib64 -Wl,--dynamic-linker=/home/share/gentoo/lib64/ld-linux-x86-64.so.2 conftest.c  >&5
/home/share/gentoo/tmp/usr/lib/gcc/x86_64-pc-linux-gnu/10.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: /lib/../lib64/Scrt1.o: in function `_start':
(.text+0x16): undefined reference to `__libc_csu_fini'
/home/share/gentoo/tmp/usr/lib/gcc/x86_64-pc-linux-gnu/10.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: (.text+0x1d): undefined reference to `__libc_csu_init'
```

We need to force GCC to use the Prefix version
of glibc we just built.

Bug: https://github.com/NixOS/nixpkgs/issues/158042
Closes: https://bugs.gentoo.org/824482
Thanks-to: Bart Oldeman <bartoldeman@gmail.com>
Thanks-to: Sergei Trofimovich <slyich@gmail.com>
Signed-off-by: Sam James <sam@gentoo.org>